Repository KinsonDigital/KdGui, pull requests merged in 2024-06, with the labels that each got.

#4 🚧Create manual testing application
  .run/KdGui Testing.run.xml
  Images/kdgui-logo.png
  KDGUI.sln
  KDGUI/ArrowButton.cs
  KDGUI/ComboBox.cs
  KDGUI/ExtensionMethods.cs
  KDGUI/Factories/ControlFactory.cs
  KDGUI/Factories/IControlFactory.cs
  KDGUI/IoC.cs
  KDGUI/KDGUI.csproj
  KDGUI/kdgui-logo.ico
  KdGui.sln.DotSettings
  README.md
  Testing/KdGuiTesting/KdGuiTesting.csproj
  Testing/KdGuiTesting/Main.cs
  Testing/KdGuiTesting/Program.cs
  Testing/KdGuiTesting/Scenes/AllControlsScene.cs
  Testing/KdGuiTesting/Scenes/ButtonScene.cs
  Testing/KdGuiTesting/stylecop.json
  Testing/KdGuiTests/KdGuiTests.csproj
Labels: cicd, high priority, preview, ⚙️config

#13 🚧Improve window auto size
  KdGui.sln.DotSettings
  KdGui/ArrowButton.cs
  KdGui/Button.cs
  KdGui/CheckBox.cs
  KdGui/ComboBox.cs
  KdGui/Control.cs
  KdGui/ControlGroup.cs
  KdGui/Core/ExtensionMethods.cs
  KdGui/Core/IImGuiInvoker.cs
  KdGui/Core/ImGuiExt.cs
  KdGui/Core/ImGuiInvoker.cs
  KdGui/ExtensionMethods.cs
  KdGui/Factories/ControlFactory.cs
  KdGui/IControlGroup.cs
  KdGui/IUpDown.cs
  KdGui/KdGui.csproj
  KdGui/Label.cs
  KdGui/NextPrevious.cs
  KdGui/RadioButton.cs
  KdGui/Slider.cs
  KdGui/UpDown.cs
  Testing/KdGuiTesting/Main.cs
  Testing/KdGuiTests/ControlGroupTests.cs
  Testing/KdGuiTests/Helpers/FakeButton.cs
  Testing/KdGuiTests/Helpers/FakeLabel.cs
  Testing/KdGuiTests/Helpers/TestHelpers.cs
  Testing/KdGuiTests/KdGuiTests.csproj
  Testing/KdGuiTests/UnitTest1.cs
Labels: high-priority, preview, ✨new-feature, 💎enhancement

#11 🚧Set up KD-Admin
  .gitignore
  create-pr.ps1
  dev-tools/bin/kd-admin
  dev-tools/bin/kd-admin.cmd
  dev-tools/create-pr-settings.json
  dev-tools/prepare-release-settings.json
  dev-tools/prev-gen-release-notes-settings.json
  dev-tools/prod-gen-release-notes-settings.json
  prepare-for-release.ps1
  templates/prev-prepare-release-template.md
  templates/prod-prepare-release-template.md
Labels: medium-priority, preview, ⚙️config
